#!/bin/bash

cp sampleData.gdf dist.gdf 
flag=$(ls | grep "^GDF$")
if [[ -z $flag ]]
then
	cd .
else
	rm -r GDF
fi

mkdir GDF
cd GDF
mkdir pred res
cd ..
filename='dist.gdf'
rel=(NaN NaN NaN NaN NaN NaN NaN)
header=(NaN NaN NaN)
IFS=$'\n'
while read line
do
	IFS='|' read -r -a rel<<<"$line"
	outfile=${rel[1]}.gdf
	cd ./GDF/res
        flag=$(ls | grep $outfile)
	if [[ -z $flag ]]
	then
	    touch $outfile
	    n1=$(grep ".*|${rel[1]}|.*|.*|.*|.*|.*" ../../dist.gdf | wc -l)
	    n2=$(grep ".*|.*|.*|${rel[1]}|.*|.*|.*" ../../dist.gdf | wc -l)
	    n3=$(grep ".*|.*|.*|.*|.*|${rel[1]}|.*" ../../dist.gdf | wc -l)
	    echo "$n1 $n2 $n3" > $outfile
	    echo 'metadata' >> $outfile
	    echo '@Subject' >> $outfile
	    echo '@Predicate' >> $outfile
	    echo '@Object' >> $outfile
	fi
	sed '/@Subject/a \'$line'' $outfile > temp
	rm $outfile
	mv temp $outfile
	outfile=${rel[5]}.gdf
	flag=$(ls | grep $outfile)
	if [[ -z $flag ]]
	then
	    touch $outfile
	    n1=$(grep ".*|${rel[5]}|.*|.*|.*|.*|.*" ../../dist.gdf | wc -l)
	    n2=$(grep ".*|.*|.*|${rel[5]}|.*|.*|.*" ../../dist.gdf | wc -l)
	    n3=$(grep ".*|.*|.*|.*|.*|${rel[5]}|.*" ../../dist.gdf | wc -l)
	    echo "$n1 $n2 $n3" > $outfile
	    echo 'metadata' >> $outfile
	    echo '@Subject' >> $outfile
	    echo '@Predicate' >> $outfile
	    echo '@Object' >> $outfile

	fi
        op='./GDF/res/'${rel[1]}'.gdf : '${rel[0]}
	sed '/@Object/a \'$op'' $outfile > temp
	rm $outfile
	mv temp $outfile
	cd ../pred
	outfile=${rel[3]}.gdf
	flag=$(ls | grep $outfile)
	if [[ -z $flag ]]
	then
	    touch $outfile
	    n1=$(grep ".*|${rel[3]}|.*|.*|.*|.*|.*" ../../dist.gdf | wc -l)
	    n2=$(grep ".*|.*|.*|${rel[3]}|.*|.*|.*" ../../dist.gdf | wc -l)
	    n3=$(grep ".*|.*|.*|.*|.*|${rel[3]}|.*" ../../dist.gdf | wc -l)
	    echo "$n1 $n2 $n3" > $outfile

	    echo 'metadata' >> $outfile
	    echo '@Subject' >> $outfile
	    echo '@Predicate' >> $outfile
	    echo '@Object' >> $outfile

	fi
	op='./GDF/res/'${rel[1]}'.gdf : '${rel[0]}
	sed '/@Predicate/a \'$op'' $outfile > temp
	rm $outfile
	mv temp $outfile
	IFS=$'\n'
	cd ../..
done < $filename
